### ISSUE TITLE
ERROR Error: NG0203 (ChatClientService).

### ISSUE THREAD

**Issue by johnnremy** [GetStream/stream-chat-angular#564]
main.ts:5 ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:3824:15)
    at ɵɵinject (core.mjs:3837:42)
    at Object.ChatClientService_Factory [as factory] (stream-chat-angular.js:4871:42)
    at core.mjs:5239:43
    at runInInjectorProfilerContext (core.mjs:3644:9)
    at R3Injector.hydrate (core.mjs:5238:17)
    at R3Injector.get (core.mjs:5106:33)
    at R3Injector.get (core.mjs:5117:33)
    at ChainedInjector.get (core.mjs:16458:36)
    at lookupTokenUsingModuleInjector (core.mjs:6711:39)
    
   main.ts:6 Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:3824:15)
    at ɵɵinject (core.mjs:3837:42)
    at Object.ChatClientService_Factory [as factory] (stream-chat-angular.js:4871:42)
    at core.mjs:5239:43
    at runInInjectorProfilerContext (core.mjs:3644:9)
    at R3Injector.hydrate (core.mjs:5238:17)
    at R3Injector.get (core.mjs:5106:33)
    at R3Injector.get (core.mjs:5117:33)
    at ChainedInjector.get (core.mjs:16458:36)
    at lookupTokenUsingModuleInjector (core.mjs:6711:39)

![Screenshot 2024-03-05 162928](https://github.com/GetStream/stream-chat-angular/assets/125705923/c89289ff-3467-4c0f-acc2-bbf4f9c4e0fd)

**Comment by szuperaz** [comment]
Hi,

It's not possible to investigate a call stack without any context or explanation. Please also provide the following information:
- Which Angular version you're using
- Which version of the Angular SDK you're using
- How do you import the `StreamChatModule`?
